parameters:
    geny.factory.repository.class: 'GenyBundle\Factory\RepositoryFactory'
    geny.form.type.builder.class: 'GenyBundle\Form\Type\BuilderType'

services:
    geny.factory.repository:
        class: '%geny.factory.repository.class%'

    geny.form.type.builder:
        class: '%geny.form.type.builder.class%'
        parent: geny.base.type
        arguments: []
        tags:
            - { name: form.type }
