parameters:
    geny.class: Fuz\GenyBundle\Services\Environment
    geny.agent.class: Fuz\GenyBundle\Services\Agent
    geny.loader.class: Fuz\GenyBundle\Services\Loader
    geny.unserializer.class: Fuz\GenyBundle\Services\Unserializer
    geny.normalizer.class: Fuz\GenyBundle\Services\Normalizer
    geny.builder.class: Fuz\GenyBundle\Services\Builder
    geny.validator.class: Fuz\GenyBundle\Services\Validator
    geny.initializer.class: Fuz\GenyBundle\Services\Initializer
    geny.form.type.container.class: Fuz\GenyBundle\Form\ContainerType

services:
    geny:
        class: %geny.class%
        arguments: [@geny.agent, @geny.loader, @geny.unserializer, @geny.normalizer, @geny.builder, @geny.validator, @geny.initializer]

    geny.agent:
        class: %geny.agent.class%
        arguments: []

    geny.loader:
        class: %geny.loader.class%
        arguments: [@file_locator]

    geny.unserializer:
        class: %geny.unserializer.class%
        arguments: []

    geny.normalizer:
        class: %geny.normalizer.class%
        arguments: [@geny.agent, @geny.loader, @geny.unserializer, @geny.validator]

    geny.builder:
        class: %geny.builder.class%
        arguments: [@form.factory]

    geny.validator:
        class: %geny.validator.class%
        arguments: [@geny.agent]

    geny.initializer:
        class: %geny.initializer.class%
        arguments: []

    geny.form.type.container:
        class: %geny.form.type.container.class%
        arguments: []
        tags:
          - { name: form.type, alias: container }
