parameters:
    geny.class: GenyBundle\Services\Environment
    geny.base.class: GenyBundle\Base\BaseService
    geny.type.class: GenyBundle\Provider\Type

services:
    geny:
        class: %geny.class%
        arguments: [@geny.extension, @geny.loader, @geny.unserializer, @geny.normalizer, @geny.validator, @geny.builder, @geny.initializer]

    geny.base:
        class: %geny.base.class%
        abstract: true
        calls:
          - [setContainer, [@service_container]]

    geny.type:
        class: %geny.type.class%
        parent: geny.base
        arguments: []
