parameters:
    geny.base.class: Fuz\GenyBundle\Base\BaseService
    geny.class: Fuz\GenyBundle\Services\Environment
    geny.agent.class: Fuz\GenyBundle\Agent\Agent
    geny.loader.class: Fuz\GenyBundle\Provider\LoaderProvider
    geny.loader.file.class: Fuz\GenyBundle\Provider\Loader\FileLoader
    geny.unserializer.class: Fuz\GenyBundle\Provider\UnserializerProvider
    geny.unserializer.json.class: Fuz\GenyBundle\Provider\Unserializer\JsonUnserializer
    geny.normalizer.class: Fuz\GenyBundle\Services\Normalizer
    geny.builder.class: Fuz\GenyBundle\Services\Builder
    geny.validator.class: Fuz\GenyBundle\Services\Validator
    geny.initializer.class: Fuz\GenyBundle\Services\Initializer
    geny.form.type.container.class: Fuz\GenyBundle\Form\ContainerType

services:
    geny.base:
        class: %geny.base.class%
        abstract: true
        calls:
          - [setContainer, [@service_container]]

    geny:
        class: %geny.class%
        arguments: [@geny.agent, @geny.loader, @geny.unserializer, @geny.normalizer, @geny.builder, @geny.validator, @geny.initializer]

    geny.agent:
        class: %geny.agent.class%
        arguments: []

    geny.loader:
        class: %geny.loader.class%
        parent: geny.base

    geny.loader.file:
        class: %geny.loader.file.class%
        arguments: [@file_locator]
        tags:
            - { name: geny.loader }

    geny.unserializer:
        class: %geny.unserializer.class%
        parent: geny.base

    geny.unserializer.json:
        class: %geny.unserializer.json.class%
        tags:
            - { name: geny.unserializer }

    geny.normalizer:
        class: %geny.normalizer.class%
        arguments: [@geny.agent, @geny.loader, @geny.unserializer, @geny.validator]

    geny.builder:
        class: %geny.builder.class%
        arguments: [@form.factory]

    geny.validator:
        class: %geny.validator.class%
        arguments: [@geny.agent]

    geny.initializer:
        class: %geny.initializer.class%
        arguments: []

    geny.form.type.container:
        class: %geny.form.type.container.class%
        arguments: []
        tags:
          - { name: form.type, alias: container }
