parameters:
    geny.class: Fuz\GenyBundle\Services\Environment
    geny.base.class: Fuz\GenyBundle\Base\BaseService
    geny.context.class: Fuz\GenyBundle\Data\Context
    geny.extension.class: Fuz\GenyBundle\Provider\Extension
    geny.extension.core.class: Fuz\GenyBundle\Provider\Extension\CoreExtension
    geny.loader.class: Fuz\GenyBundle\Provider\Loader
    geny.loader.file.class: Fuz\GenyBundle\Provider\Loader\FileLoader
    geny.unserializer.class: Fuz\GenyBundle\Provider\Unserializer
    geny.unserializer.json.class: Fuz\GenyBundle\Provider\Unserializer\JsonUnserializer
    geny.normalizer.class: Fuz\GenyBundle\Provider\Normalizer
    geny.normalizer.form.class: Fuz\GenyBundle\Provider\Normalizer\FormNormalizer
    geny.normalizer.type.class: Fuz\GenyBundle\Provider\Normalizer\TypeNormalizer
    geny.normalizer.option.class: Fuz\GenyBundle\Provider\Normalizer\OptionNormalizer
    geny.normalizer.validator.class: Fuz\GenyBundle\Provider\Normalizer\ValidatorNormalizer
    geny.provider.class: Fuz\GenyBundle\Services\Provider
    geny.validator.class: Fuz\GenyBundle\Provider\Validator
    geny.validator.form.class: Fuz\GenyBundle\Provider\Validator\FormValidator
    geny.validator.type.class: Fuz\GenyBundle\Provider\Validator\TypeValidator
    geny.validator.option.class: Fuz\GenyBundle\Provider\Validator\OptionValidator
    geny.validator.validator.class: Fuz\GenyBundle\Provider\Validator\ValidatorValidator
    geny.builder.class: Fuz\GenyBundle\Provider\Builder
    geny.builder.form.class: Fuz\GenyBundle\Provider\Builder\FormBuilder
    geny.builder.type.class: Fuz\GenyBundle\Provider\Builder\TypeBuilder
    geny.builder.option.class: Fuz\GenyBundle\Provider\Builder\OptionBuilder
    geny.builder.validator.class: Fuz\GenyBundle\Provider\Builder\ValidatorBuilder

    geny.initializer.class: Fuz\GenyBundle\Services\Initializer
    geny.form.type.container.class: Fuz\GenyBundle\Form\ContainerType

services:
    geny:
        class: %geny.class%
        arguments: [@geny.extension, @geny.loader, @geny.unserializer, @geny.normalizer, @geny.builder, @geny.validator, @geny.initializer]

    geny.base:
        class: %geny.base.class%
        abstract: true
        calls:
          - [setContainer, [@service_container]]

    geny.context:
        class: %geny.context.class%
        arguments: []

    geny.extension:
        class: %geny.extension.class%
        parent: geny.base
        arguments: []

    geny.extension.core:
        class: %geny.extension.core.class%
        arguments: []
        tags:
            - { name: geny.extension }

    geny.loader:
        class: %geny.loader.class%
        parent: geny.base
        arguments: []

    geny.loader.file:
        class: %geny.loader.file.class%
        arguments: [@file_locator]
        tags:
            - { name: geny.loader }

    geny.unserializer:
        class: %geny.unserializer.class%
        parent: geny.base
        arguments: []

    geny.unserializer.json:
        class: %geny.unserializer.json.class%
        tags:
            - { name: geny.unserializer }

    geny.normalizer:
        class: %geny.normalizer.class%
        parent: geny.base
        arguments: []

    geny.normalizer.form:
        class: %geny.normalizer.form.class%
        parent: geny.base
        tags:
            - { name: geny.normalizer }

    geny.normalizer.type:
        class: %geny.normalizer.type.class%
        parent: geny.base
        tags:
            - { name: geny.normalizer }

    geny.normalizer.option:
        class: %geny.normalizer.option.class%
        parent: geny.base
        tags:
            - { name: geny.normalizer }

    geny.normalizer.validator:
        class: %geny.normalizer.validator.class%
        parent: geny.base
        tags:
            - { name: geny.normalizer }

    geny.provider:
        class: %geny.provider.class%
        parent: geny.base
        arguments: []

    geny.validator:
        class: %geny.validator.class%
        parent: geny.base
        arguments: []

    geny.validator.form:
        class: %geny.validator.form.class%
        parent: geny.base
        tags:
            - { name: geny.validator }

    geny.validator.type:
        class: %geny.validator.type.class%
        parent: geny.base
        tags:
            - { name: geny.validator }

    geny.validator.option:
        class: %geny.validator.option.class%
        parent: geny.base
        tags:
            - { name: geny.validator }

    geny.validator.validator:
        class: %geny.validator.validator.class%
        parent: geny.base
        tags:
            - { name: geny.validator }

    geny.builder:
        class: %geny.builder.class%
        parent: geny.base
        arguments: []

    geny.builder.form:
        class: %geny.builder.form.class%
        parent: geny.base
        tags:
            - { name: geny.builder }

    geny.builder.type:
        class: %geny.builder.type.class%
        parent: geny.base
        tags:
            - { name: geny.builder }

    geny.builder.option:
        class: %geny.builder.option.class%
        parent: geny.base
        tags:
            - { name: geny.builder }

    geny.builder.validator:
        class: %geny.builder.validator.class%
        parent: geny.base
        tags:
            - { name: geny.builder }

    geny.initializer:
        class: %geny.initializer.class%
        parent: geny.base
        arguments: []

    geny.form.type.container:
        class: %geny.form.type.container.class%
        arguments: []
        tags:
          - { name: form.type, alias: container }
