parameters:
    geny.class: GenyBundle\Services\Environment
    geny.base.class: GenyBundle\Base\BaseService

services:
    geny:
        class: %geny.class%
        arguments: [@geny.extension, @geny.loader, @geny.unserializer, @geny.normalizer, @geny.validator, @geny.builder, @geny.initializer]

    geny.base:
        class: %geny.base.class%
        abstract: true
        calls:
          - [setContainer, [@service_container]]

#    geny.extension:
#        class: %geny.extension.class%
#        parent: geny.base
#        arguments: []
