parameters:
    geny.form.type.field_builder.class: 'GenyBundle\Form\Type\FieldBuilderType'
    geny.form.type.form_builder.class: 'GenyBundle\Form\Type\FormBuilderType'
    geny.form.type.submit_builder.class: 'GenyBundle\Form\Type\SubmitBuilderType'
    geny.form.extension.collection.class: 'GenyBundle\Form\Extension\CollectionTypeExtension'

services:
    geny.form.type.field_builder:
        class: '%geny.form.type.field_builder.class%'
        parent: geny.base.type
        arguments: []
        tags:
            - { name: form.type }

    geny.form.type.form_builder:
        class: '%geny.form.type.form_builder.class%'
        parent: geny.base.type
        arguments: []
        tags:
            - { name: form.type }

    geny.form.type.submit_builder:
        class: '%geny.form.type.submit_builder.class%'
        parent: geny.base.type
        arguments: []
        tags:
            - { name: form.type }

    geny.form.extension.collection:
        class: '%geny.form.extension.collection.class%'
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }
